spring.application.name=library-api

# --- Database connection ---
spring.datasource.url=jdbc:postgresql://localhost:5432/library
spring.datasource.username=library
spring.datasource.password=library

# --- JPA / Hibernate ---
# 'update' lets Hibernate auto-create/alter tables from @Entity classes.
# Fine for learning; in production you'd use Flyway or Liquibase migrations instead.
spring.jpa.hibernate.ddl-auto=update
# Logs every SQL statement Hibernate runs — great for learning what JPA is doing.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#management.endpoints.web.exposure.include = health,info
# expose all actuator endpoints
management.endpoints.web.exposure.include =*
management.info.env.enabled = true

info.app.name = Library Management
info.app.description = An app to manage Library book transactions
info.app.version = 1.0.0
